# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Create and set up rnaturalearth cache
        run: |
          mkdir -p rnaturalearth_cache
          echo "R_NATURALEARTH_CACHE_DIR=rnaturalearth_cache" >> $GITHUB_ENV
          Rscript -e 'options(rnaturalearth.cache_dir = Sys.getenv("R_NATURALEARTH_CACHE_DIR"))'
        shell: bash

      - name: Download medium-scale rnaturalearth data
        run: |
          # Explicitly use the new cache directory
          Rscript -e 'rnaturalearth::ne_download(scale = "medium", type = "countries", category = "cultural", destdir = Sys.getenv("R_NATURALEARTH_CACHE_DIR"))'
          Rscript -e 'rnaturalearth::ne_download(scale = "medium", type = "coastline", category = "physical", destdir = Sys.getenv("R_NATURALEARTH_CACHE_DIR"))'
          Rscript -e 'rnaturalearth::ne_download(scale = "medium", type = "sovereignty", category = "cultural", destdir = Sys.getenv("R_NATURALEARTH_CACHE_DIR"))'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
